const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  createTab: () => ipcRenderer.send('create-tab'),
  switchTab: (id) => ipcRenderer.send('switch-tab', id),
  closeTab: (id) => ipcRenderer.send('close-tab', id),
  clearTab: (id) => ipcRenderer.send('clear-tab', id),
  refreshTab: (id) => ipcRenderer.send('refresh-tab', id),
  renameTab: (id, name) => ipcRenderer.send('rename-tab', { tabId: id, name }),
  toggleMuteTab: (id) => ipcRenderer.send('toggle-mute-tab', id),
  reorderTabs: (from, to) => ipcRenderer.send('reorder-tabs', { fromIndex: from, toIndex: to }),
  sidebarToggled: (visible) => ipcRenderer.send('sidebar-toggled', visible),
  nextTab: () => ipcRenderer.send('next-tab'),
  prevTab: () => ipcRenderer.send('prev-tab'),
  minimize: () => ipcRenderer.send('minimize'),
  maximize: () => ipcRenderer.send('maximize'),
  close: () => ipcRenderer.send('close'),
  showContextMenu: (id) => ipcRenderer.send('show-context-menu', id),
  updateBadge: (dataUrl) => ipcRenderer.send('update-badge', dataUrl),
  onTabCreated: (cb) => ipcRenderer.on('tab-created', (_, data) => cb(data)),
  onTabSwitched: (cb) => ipcRenderer.on('tab-switched', (_, id) => cb(id)),
  onTabClosed: (cb) => ipcRenderer.on('tab-closed', (_, id) => cb(id)),
  onTabMuted: (cb) => ipcRenderer.on('tab-muted', (_, data) => cb(data)),
  onTabUnread: (cb) => ipcRenderer.on('tab-unread', (_, data) => cb(data)),
  onTabRenamed: (cb) => ipcRenderer.on('tab-renamed', (_, data) => cb(data)),
  onTabsReordered: (cb) => ipcRenderer.on('tabs-reordered', (_, ids) => cb(ids)),
  onThemeChanged: (cb) => ipcRenderer.on('theme-changed', (_, theme) => cb(theme)),
  onStartRename: (cb) => ipcRenderer.on('start-rename', (_, id) => cb(id)),
  onDrawBadge: (cb) => ipcRenderer.on('draw-badge', (_, count) => cb(count)),
});